CREATE TABLE BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    CONSTRAINT UK_JOB_INSTANCE_KEY UNIQUE (JOB_KEY)
);

CREATE TABLE BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    STATUS VARCHAR(10) NOT NULL,
    EXIT_CODE VARCHAR(10),
    EXIT_MESSAGE VARCHAR(2500),
    VERSION BIGINT,
    CONSTRAINT FK_JOB_INSTANCE FOREIGN KEY (JOB_INSTANCE_ID) REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    JOB_PARAM_KEY VARCHAR(100) NOT NULL,
    JOB_PARAM_VALUE VARCHAR(1000),
    TYPE_CD VARCHAR(6),
    IDENTIFIER BIGINT,
    CONSTRAINT FK_JOB_EXECUTION FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    STATUS VARCHAR(10) NOT NULL,
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE VARCHAR(10),
    EXIT_MESSAGE VARCHAR(2500),
    VERSION BIGINT,
    CONSTRAINT FK_STEP_EXECUTION FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(1000),
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT FK_STEP_EXECUTION_CONTEXT FOREIGN KEY (STEP_EXECUTION_ID) REFERENCES BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(1000),
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT FK_JOB_EXECUTION_CONTEXT FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);
